# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_football', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='goals_sum',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
