# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-06 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_football', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='draws',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='loses',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='wins',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
