# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 08:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_football', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='energy',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
