# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_football', '0002_team_goals_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player_id',
            field=models.IntegerField(default=None),
        ),
    ]
