# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_football', '0002_team_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
