# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_football', '0003_team_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='loses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
